# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0002_auto_20170705_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.Trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_app.User')),
            ],
        ),
    ]
