# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_joint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joint',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='user',
        ),
        migrations.AddField(
            model_name='joint',
            name='trip_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joint',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
