# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_auto_20170706_0833'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='joint',
            managers=[
                ('jointManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='joint',
            name='trip_id',
        ),
        migrations.RemoveField(
            model_name='joint',
            name='user_id',
        ),
        migrations.AddField(
            model_name='joint',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_app.Trip'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joint',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travel_app.User'),
            preserve_default=False,
        ),
    ]
